title: Quantum Computing Deadlines Hub
description: Stay updated with the latest deadlines for quantum events, including conferences, journals, and workshops. Never miss an important submission again!
author: Ziqing Guo

domain: "https://qcddl.ziqguo.com"
baseurl: ""

twitter_username: Martinetin_
github_username: gzquse
github_repo: qcddl
ga_id: G-8QMW426VWE

markdown: kramdown
plugins:
  - jekyll-remote-theme
remote_theme: pages-themes/cayman